
window.dnn=dnn||{};window.dnn.modules=dnn.modules||{};window.dnn.modules.publisher=dnn.modules.publisher||{};window.dnn.modules.publisher.CardViewManager=(function($,ko){"use strict";var configuration;var viewModel={loading:ko.observable(false),postList:ko.observableArray(),loadMoreVisible:ko.observable(true),isFiltered:ko.observable(),searchText:ko.observable(),selectedTags:ko.observableArray(),selectedAuthor:ko.observable(null),emptyListPlaceholderVisible:ko.observable(),latestPostsTitleVisible:ko.observable()};var itemIndex;viewModel.openDetail=function(post){window.location.href=post.detailsUrl;};viewModel.touchStart=function(detailsUrl,e){var card=$(e.currentTarget);if(!card.hasClass('active')){$(".publishcard.small-card.active").removeClass('active');card.addClass('active');}else{window.location.href=detailsUrl;}};viewModel.backgroundImage=function(post){return post.mainImageUrl?'url('+post.mainImageUrl+')':null;};function requestCardPage(query){viewModel.loading(true);dnn.modules.publisher.RequestUtils.request('Publisher','ViewPost','Search','GET',query,function(data){if(data.length>0){ko.utils.arrayPushAll(viewModel.postList,data);itemIndex+=configuration.pageSize;}
viewModel.emptyListPlaceholderVisible(viewModel.postList().length===0);viewModel.latestPostsTitleVisible(!viewModel.isFiltered()&&!viewModel.emptyListPlaceholderVisible());viewModel.loadMoreVisible(data.length===configuration.pageSize);},null,function(){viewModel.loading(false);});}
viewModel.loadMore=function(){var queryParameters=dnn.modules.publisher.RequestUtils.getQueryParameters();var query={startIndex:itemIndex,endIndex:itemIndex+configuration.pageSize-1,moduleId:configuration.moduleId,excludePostIds:configuration.excludePostIds,author:queryParameters.author,tags:queryParameters.tags,text:queryParameters.text};requestCardPage(query);};function clearStaticallyRenderedCards(){$(configuration.bindingElementSelector).find("div.card-container > div.publishcard").remove();}
function getUrl(url,params){var query=$.param(params).replace(/%2C/g,",");if(query.length>0){return url+"?"+query;}
return url;}
function historySupported(){return window.history&&window.history.pushState;}
function search(params){var url=getUrl(configuration.listUrl,params);if(!historySupported()){window.location.href=url;return;}
history.pushState({publisher:true},null,url);viewModel.isFiltered(params["text"]||params["tags"]||params["author"]);var query={startIndex:1,endIndex:configuration.pageSize,moduleId:configuration.moduleId,author:params.author,tags:params.tags,text:params.text};clearStaticallyRenderedCards();itemIndex=1;viewModel.postList.removeAll();requestCardPage(query);}
function updateViewModelFromQuery(){var params=dnn.modules.publisher.RequestUtils.getQueryParameters();viewModel.searchText(params["text"]);viewModel.selectedTags.removeAll();var tags=params["tags"];if(tags){ko.utils.arrayPushAll(viewModel.selectedTags,tags.split(","));}
var authorUserId=params["author"];if(authorUserId){viewModel.selectedAuthor({key:authorUserId,name:configuration.selectedAuthorName});}else{viewModel.selectedAuthor(null);}}
function updateQueryParameter(name,value){var params=dnn.modules.publisher.RequestUtils.getQueryParameters();if((!value||value.length===0)){if(params[name]){delete params[name];search(params);}}else{if(params[name]!==value){params[name]=value;search(params);}}}
function init(config){configuration=config;itemIndex=config.pageSize+1;var queryParameters=dnn.modules.publisher.RequestUtils.getQueryParameters();viewModel.isFiltered(queryParameters["text"]||queryParameters["tags"]||queryParameters["author"]);viewModel.isFiltered.subscribe(function(value){$("body").trigger("publisher.filteredChanged",{isFiltered:value});});var viewModelBinding=$(config.bindingElementSelector);var node=viewModelBinding[0];if(ko.dataFor(node)){ko.cleanNode(node);}
viewModel.emptyListPlaceholderVisible(config.isFirstLoadEmpty);viewModel.latestPostsTitleVisible(config.latestPostsTitleVisible);ko.applyBindings(viewModel,node);viewModelBinding.find(".publishcard h2").dotdotdot();viewModelBinding.find(".publishcard div.story").dotdotdot();updateViewModelFromQuery();viewModel.searchText.subscribe(function(text){updateQueryParameter("text",text);});viewModel.selectedTags.subscribe(function(tags){updateQueryParameter("tags",tags.join(","));});viewModel.selectedAuthor.subscribe(function(author){updateQueryParameter("author",author?author.key:null);});if(historySupported()){history.replaceState({publisher:true},null);window.onpopstate=function(event){if(!event.state||!event.state.publisher){return;}
window.location.reload();};}}
return{init:init,search:search,searchText:viewModel.searchText,selectedTags:viewModel.selectedTags,selectedAuthor:viewModel.selectedAuthor};})(jQuery||$,ko);