
window.dnn=dnn||{};window.dnn.modules=dnn.modules||{};window.dnn.modules.publisher=dnn.modules.publisher||{};window.dnn.modules.publisher.EditPostDetailsManager=(function($,ko){"use strict";var requestService,config,viewModel;var init,createViewModel,show,hide,save,cancel,tmpModel,makeCopyOfTheInitialModel,restoreCopyOfTheInitialModel,onSaveCallback200,getUpdatePostMetadataPayloadFromModel,refreshModelWithServerData,isModelValid,isSlugValid,isSlugInUse,syncTitleAndBody,getDescriptionFromBody,isPostCreation;ko.extenders.dirty=function(target,option){target.dirty=option;target.subscribe(function(newValue){target.dirty=true;});return target;};init=function(configuration){config=configuration;requestService=dnn.modules.publisher.RequestUtils;requestService.init(config.moduleId);createViewModel(config);var viewModelBinding=$(config.bindingElementSelector);ko.applyBindings(viewModel,viewModelBinding[0]);};isSlugValid=function(slug){var result;requestService.request("Publisher","EditPost","IsValidSlug","GET",{slug:slug},function(data){result=data.isValid;},null,null,true);return result;};isSlugInUse=function(slug){var result,data={slug:slug,currentSlug:null};if(!isPostCreation){if(!tmpModel){return false;}
data.currentSlug=tmpModel.slug;}
requestService.request("Publisher","EditPost","IsSlugInUse","GET",data,function(data){result=data.isInUse;},null,null,true);return result;};createViewModel=function(config){isPostCreation=config.contentItemId===0;viewModel={isPostCreation:isPostCreation,visible:ko.observable(false),cancel:cancel,hide:hide,save:save,publisherUrl:config.listUrl,model:{tags:ko.observable(config.post.tags.join()),title:ko.observable(config.post.metadataTitle).extend({required:{params:true,message:config.resx.titleIsRequired,onlyIf:function(){return!isPostCreation;}},dirty:false}),description:ko.observable(config.post.metadataDescription).extend({dirty:false}),allowedComments:ko.observable(config.post.allowedComments),featured:ko.observable(config.post.featured),slug:ko.observable(config.post.slug).extend({required:{params:true,message:config.resx.urlIsRequired,onlyIf:function(){return!isPostCreation;}},validation:[{validator:function(val){if(val.trim()===''){return true;}
return isSlugValid(val);},message:config.resx.urlIsNotValid},{validator:function(val){if(val.trim()===''){return true;}
return!isSlugInUse(val);},message:config.resx.urlIsInUse}]})},validationOptions:{errorMessageClass:"dnnFormMessage dnnFormError"}};};makeCopyOfTheInitialModel=function(){var model=viewModel.model;tmpModel={tags:model.tags(),title:model.title(),description:model.description(),allowedComments:model.allowedComments(),featured:model.featured(),slug:model.slug()};};restoreCopyOfTheInitialModel=function(){var model=viewModel.model;if(!tmpModel){return;}
model.tags(tmpModel.tags);model.title(tmpModel.title);model.description(tmpModel.description);model.allowedComments(tmpModel.allowedComments);model.featured(tmpModel.featured);model.slug(tmpModel.slug);};refreshModelWithServerData=function(data){if(!data){return;}
viewModel.model.title(data.MetadataTitle);viewModel.model.description(data.MetadataDescription);viewModel.model.slug(data.Slug);viewModel.model.featured(data.Featured);viewModel.model.allowedComments(data.AllowedComments);viewModel.model.tags(data.Tags.join());};getUpdatePostMetadataPayloadFromModel=function(){var model=viewModel.model;return{contentItemId:config.contentItemId,tags:model.tags().split(","),metadataTitle:model.title(),metadataDescription:model.description(),allowedComments:model.allowedComments(),featured:model.featured(),slug:model.slug()};};onSaveCallback200=function(data){refreshModelWithServerData(data);makeCopyOfTheInitialModel();hide();};isModelValid=function isModelValid(){var validatedViewModel=ko.validatedObservable(viewModel.model);return validatedViewModel.isValid();};save=function(){if(!isModelValid()){return;}
var data=getUpdatePostMetadataPayloadFromModel();requestService.request("Publisher","EditPost","UpdatePostMetadata","POST",data,onSaveCallback200);};cancel=function(){if(!isPostCreation){restoreCopyOfTheInitialModel();}
viewModel.visible(false);};show=function(){if(!isPostCreation){makeCopyOfTheInitialModel();}
viewModel.visible(true);};hide=function(){viewModel.visible(false);};syncTitleAndBody=function syncTitleAndBodyHandler(data){if(!isPostCreation){return;}
var m=viewModel.model;if(!m.title.dirty){m.title(data.title);m.title.dirty=false;}
if(!m.description.dirty){m.description(getDescriptionFromBody(data.body));m.description.dirty=false;}};getDescriptionFromBody=function getDescriptionFromBodyHandler(body){var tempDiv=document.createElement("DIV");tempDiv.innerHTML=body;var text=tempDiv.innerText||tempDiv.textContent;return text.replace(/\t/g,"").replace(/\n/g,"").trim().substr(0,255);};return{init:init,show:show,hide:hide,getPostMetadata:getUpdatePostMetadataPayloadFromModel,syncTitleAndBody:syncTitleAndBody,isModelValid:isModelValid};}(jQuery||$,ko));