
window.dnn=dnn||{};window.dnn.modules=dnn.modules||{};window.dnn.modules.publisher=dnn.modules.publisher||{};window.dnn.modules.publisher.UploadManager=(function($,ko){"use strict";var onImageUploaded,getImages,config,browserSupportsDragDrop;var viewModel={activeTab:ko.observable("upload-file"),draggingOver:ko.observable(false),uploading:ko.observable(false),uploadPercent:ko.observable(0),uploadUrl:ko.observable(),uploadingFromUrl:ko.observable(false),previewAvailable:ko.observable(false),searchInput:ko.observable(null),selectedFileId:ko.observable(null),currentFolder:ko.observable({key:-1}),storedFiles:ko.observableArray()};viewModel.activateTab=function(d,e){var tab=e.target.attributes.href.nodeValue.substring(1);viewModel.activeTab(tab);};viewModel.dragOver=function(){if(browserSupportsDragDrop()){viewModel.draggingOver(true);}};viewModel.dragLeave=function(){viewModel.draggingOver(false);};viewModel.uploadFromUrl=function(){if(!viewModel.uploadUrl()||!viewModel.previewAvailable)return;viewModel.uploadingFromUrl(true);var data={url:viewModel.uploadUrl()};dnn.modules.publisher.RequestUtils.request('Publisher','FileUpload','UploadFromUrl','POST',data,onImageUploaded,null,function(){viewModel.uploadingFromUrl(false);});};viewModel.previewUrl=ko.computed(function(){viewModel.previewAvailable(true);return viewModel.uploadUrl();}).extend({throttle:500});viewModel.hidePreview=function(){viewModel.previewAvailable(false);};viewModel.searchText=ko.computed(function(){return viewModel.searchInput();}).extend({throttle:500});viewModel.searchText.subscribe(function(){getImages();});viewModel.itemClick=function(d,e){if(d.type==='folder'){viewModel.currentFolder({key:d.id,value:d.title,path:d.path});getImages();}else{viewModel.selectedFileId(d.id);}};viewModel.setStoredImage=function(){if(viewModel.selectedFileId()==null){return;}
var data={fileId:viewModel.selectedFileId()};dnn.modules.publisher.RequestUtils.request('Publisher','FileUpload','setStoredImage','POST',data,onImageUploaded);};viewModel.selectedFolderChanged=function(folder){viewModel.currentFolder(folder);viewModel.searchInput('');viewModel.selectedFileId(null);getImages(false);};function supportAjaxUpload(){var xhr=new XMLHttpRequest;return!!(xhr&&('upload'in xhr)&&('onprogress'in xhr.upload));}
browserSupportsDragDrop=function(){return('draggable'in document.createElement('span'));};function initFileUpload(wrapper){var url=dnn.modules.publisher.RequestUtils.getServiceUrl("Publisher","FileUpload")+"UploadFile";if(!supportAjaxUpload()){var antiForgeryToken=$('input[name="__RequestVerificationToken"]').val();url+='?__RequestVerificationToken='+antiForgeryToken+'&ModuleId='+config.moduleId+'&TabId='+config.tabId;}
var uploader=wrapper.find("#uploader");uploader.fileupload({url:url,beforeSend:dnn.modules.publisher.RequestUtils.setHeaders,replaceFileInput:false,dropZone:wrapper.find("div.droparea"),submit:function(e,d){viewModel.uploading(true);if(!d.formData){d.formData={};}
return true;},done:function(e,d){var result=supportAjaxUpload()?d.result:$("pre",d.result).html();onImageUploaded(result);},always:function(){viewModel.uploading(false);viewModel.draggingOver(false);},error:function(e,d,message){dnn.modules.publisher.RequestUtils.showError(e);},progress:function(e,data){var percent=data.loaded*100/data.total;viewModel.uploadPercent(percent);}});if(!browserSupportsDragDrop()){uploader.parent().addClass("not-supported");}}
function setOnImageUploaded(onImageUploadedCallback){onImageUploaded=onImageUploadedCallback;}
getImages=function(){var params={keyword:viewModel.searchText(),folderId:viewModel.currentFolder().key,loadRecent:viewModel.currentFolder().key===-1,permission:'READ,ADD'};viewModel.storedFiles.removeAll();dnn.modules.publisher.RequestUtils.request('DNNCorp/EvoqLibrary','Redactor','getimages','GET',params,function(data){ko.utils.arrayPushAll(viewModel.storedFiles,data);});};function init(configurations){config=configurations;var viewModelBinding=$(config.bindingElementSelector);var node=viewModelBinding[0];if(ko.dataFor(node)){ko.cleanNode(node);}
ko.applyBindings(viewModel,node);initFileUpload(viewModelBinding);getImages();}
return{init:init,setOnImageUploaded:setOnImageUploaded};})(jQuery||$,ko);