
window.dnn=window.dnn||{};window.dnn.HTMLPro=window.dnn.HTMLPro||{};(function IIFE(){var InlineEditingClass;InlineEditingClass=(function IIFE(){'use strict';var TIME_TO_AUTOSAVE,TIME_PROGRESS_BAR_SAVE_LAYER,ESC,TIME_TO_PREVENT_OTHER_MODULES_OPENED,TIME_OUT_FOR_WAITING_RESOURCES,_imageEditing,isRedactorInit,_history,_culture,_resxInlineEditor,_resxImageEditing,_resxRedactor,_maxFileSize,_savingLayer,_editorMask,_inFullscren,_beforeAdvancedWasInFullScreen,_moduleWithRedactor,_autoSave,_redactorFacadeConfiguration,_changeCallbackEnabled,configServiceFramework,bindModule,initRedactor,initRedactorWithResourcesLoaded,cleanHtml,isTheSameHtmlContent,saveEditor,autosaveEditor,destroyEditor,initInterval,endInterval,showHideCodeEditor,initImageEditing,bindImageEditing,unbindImageEditing,injectAdvancedButton,advancedButtonSaveCallback,localize,linkImage,unlinkImage,executingBlurCallback,loadRedactorResources,areRedactorResourcesLoaded;InlineEditing.class='InlineEditing';InlineEditing.type='Class';TIME_TO_AUTOSAVE=5000;TIME_PROGRESS_BAR_SAVE_LAYER=4000;ESC=27;TIME_TO_PREVENT_OTHER_MODULES_OPENED=300;TIME_OUT_FOR_WAITING_RESOURCES=100;_savingLayer='<div class="dnnInlineEditingSavingLayer">'+'<div class="loopBar">'+'<div class="progressA" style="width: 0;"></div>'+'</div>'+'<div class="optacityLayer">'+'<h1 style="">{0}</h1>'+'</div>'+'</div>';_editorMask='<div class="dnnInlineEditingMask" style="display: block; position: absolute; top: 0; width: 100%; height: 100%; cursor: pointer; min-height:12px; background-color:#fff;opacity:0"></div>';_resxInlineEditor={emptyEditContentText:'Click here to edit content',advancedEditor:'Advanced Editor',errorSavingText:'Error saving the HTML content',savingChanges:'Saving changes...'};function InlineEditing(options,resx){var moduleId;this.moduleId=null;this.clientId=null;this.emptyEditContentText=null;this.module=null;this.redactorFacade=null;this.sfImage=null;this.siteRoot=null;this.storedHtml=null;this.destroyed=null;this.changes=null;this.uploadUrl=null;this.getImage=null;this.saveInterval=null;this.visual=false;_resxRedactor={};moduleId=parseInt(options.moduleId,10);if(isNaN(moduleId)){throw'moduleId not present';}
this.moduleId=moduleId;if(!options.clientId){throw'clientId not present';}
this.clientId=''+options.clientId;if(resx.culture&&typeof resx.culture==='string'){_culture=resx.culture.replace('-','_');}else{_culture='en';}
if(resx.inlineEditor&&typeof resx.inlineEditor==='object'&&Object.keys(resx.inlineEditor).length>0){_resxInlineEditor=resx.inlineEditor;}
if(resx.imageEditing&&typeof resx.imageEditing==='object'&&Object.keys(resx.imageEditing).length>0){_resxImageEditing=resx.imageEditing;}
if(resx.redactor&&typeof resx.redactor==='object'&&Object.keys(resx.redactor).length>0){_resxRedactor=resx.redactor;}
this.redactorFacade=window.dnn.HTMLPro.RedactorFacade();_redactorFacadeConfiguration={maxFileSize:options.maxFileSize||5000000}
this.redactorFacade.setConfig(_redactorFacadeConfiguration);_maxFileSize=options.maxFileSize||5000000;localize();if(!options.canUpload){options.canUpload=false;}
this.canUpload=options.canUpload;this.onChangeCallback=options.onChangeCallback;this.onEditorInitCallback=options.onEditorInitCallback;this.editUrl=options.editUrl;this.saveUrl=options.saveUrl;this.externalSaveSuccessCallback=options.saveSuccessCallback;this.module=$('#'+this.clientId);this.redactorFacade.setModule(this.module);this.editorMask=null;this.autoSaveEnabled=options.autoSaveEnabled===undefined?true:options.autoSaveEnabled;_autoSave=this.autoSaveEnabled;configServiceFramework.call(this);loadRedactorResources.call(this,resx,function(resxInformation){_resxRedactor=resxInformation.redactor;_culture=resxInformation.culture;});bindModule.call(this,this);}
loadRedactorResources=function loadRedactorResourcesHandler(resxInformation,loadedCallback){var self,localizationOptionsRedactor;self=this;if(!resxInformation.redactor){resxInformation.redactor=true;localizationOptionsRedactor={service:'DNNCorp/EvoqLibrary',controller:'Localization',resxName:'RedactorResx',resourceSettings:{method:'GetRedactorSettings',callback200:function(data){if(!resxInformation.culture||resxInformation.culture!==data.culture){resxInformation.culture=data.culture;}}},resources:{method:'GetRedactor',paramName:'localization',callback200:function(data){resxInformation.redactor=data.localization;resxInformation.culture=resxInformation.culture||'en';if(typeof loadedCallback=='function'){loadedCallback(resxInformation);}},callbackError:function(data){console.log('Error',data);}}};new dnn.utils.Localization(localizationOptionsRedactor);}else{if(typeof loadedCallback=='function'){loadedCallback(resxInformation);}}};configServiceFramework=function(){var antiForgeryToken=$('input[name="__RequestVerificationToken"]').val();this.sfImage=$.ServicesFramework(this.moduleId);this.siteRoot=this.sfImage.getServiceRoot('DNNCorp/EvoqLibrary').replace("API/","");this.siteImageRoot=this.sfImage.getServiceRoot('DNNCorp/EvoqLibrary')+'Redactor/';this.uploadUrl=this.canUpload?this.siteImageRoot+'postimages?moduleId='+this.moduleId+'&__RequestVerificationToken='+antiForgeryToken:null;this.getImage=this.siteImageRoot+'getimages';};function showEditorMask($editorMask)
{$editorMask.css("background-color","transparent");$editorMask.css("opacity","1");}
function hideEditorMask($editorMask){$editorMask.css("background-color","#fff");$editorMask.css("opacity","0");}
function isContentEmpty(html){var $html,tagsToDelete;tagsToDelete=['p','br'];$html=$("<div/>").append(html);$html.find(tagsToDelete.join(',')).each(function(){var $el=$(this);var text=$el.text();text=text.replace(/\u200B/g,'');text=text.replace(/&nbsp;/gi,'');text=text.replace(/\s/g,'');if(text===''&&$el.children().length===0){$el.remove();}});return $html.html()==="";};function addEditorMask(){var self=this;self.editorMask=$(_editorMask);var hasNoContent=isContentEmpty(self.module.html());if(hasNoContent||self.module.height()===0||self.module.width()===0){if(hasNoContent){self.editorMask.html(_resxInlineEditor.emptyEditContentText);}
showEditorMask(self.editorMask);}else{hideEditorMask(self.editorMask);}
self.editorMask.insertAfter(self.module);self.editorMask.on('click',function initRedactorHandler(evt){evt.preventDefault();if(self.isRedactorInit){return;}
setTimeout(function(){initRedactor.call(self);},TIME_TO_PREVENT_OTHER_MODULES_OPENED);});}
function removeEditorMask(){var self=this;if(!self.editorMask){return;}
self.editorMask.remove();self.editorMask=null;}
function isImageEditingInProgress(){return _imageEditing&&_imageEditing.isEditingInProcess();}
bindModule=function(self){$('div.DnnModule-'+this.moduleId).on('editmodule',function(){var $module=$(this);if(self.isRedactorInit){return;}
initRedactor.call(self);setTimeout(function(){var $img,src;$img=$module.find('.redactor-editor img').last();if($img.length>0){src=$img.attr('src');$img.on('load',function load(){var $editor,offsetTop;$editor=$module.find('.redactor-editor');offsetTop=$img.offset().top-$editor.offset().top-$('#image-edit-bar').outerHeight(true);setTimeout(function(){$img.click();$editor.scrollTop(offsetTop);},100);}).attr('src','').attr('src',src);}
if(_beforeAdvancedWasInFullScreen){$('.re-fullscreen').trigger('click');_beforeAdvancedWasInFullScreen=false;}},0);});addEditorMask.call(self);};initInterval=function(){var self=this;endInterval.call(this);this.saveInterval=setInterval(function(){autosaveEditor.call(self);},TIME_TO_AUTOSAVE);};endInterval=function(){if(this.saveInterval){clearInterval(this.saveInterval);}};showHideCodeEditor=function(){var self=this;this.visual=!this.visual;unbindImageEditing.call(this);if(_imageEditing){_history=_imageEditing.getHistory();_imageEditing.destroy(function nullifyImageAndSyncEditing(){_imageEditing=null;self.redactorFacade.sync();if(!self.visual){self.changes=true;}
self.redactorFacade.toggle();});}else{if(!this.visual){this.changes=true;}
this.redactorFacade.toggle();initImageEditing.call(this);if(_history){_imageEditing.setHistory(_history);_history=null;}}}
var initRedactorCallback,postInitRedactorCallback,blurCallback,focusCallback,changeCallback,imageUploadCallback,customToolbarEventCallback,addLinkToImage,removeLinkFromImage;addLinkToImage=function addLinkToImage(inlineEditor){inlineEditor.redactorFacade.hideModalInsertLinkTextElements();_imageEditing.removeWrappers();};removeLinkFromImage=function removeLinkFromImage(inlineEditor){var imageToUnlink;imageToUnlink=_imageEditing.getActiveImage();_imageEditing.removeWrappers();unlinkImage(imageToUnlink);_imageEditing.addWrappers();};customToolbarEventCallback=function customToolbarEventCallback(event,inlineEditor){if(_imageEditing){_imageEditing.stopEditingImage();_imageEditing.addWrappers();}};postInitRedactorCallback=function postInitRedactorCallbackHandler(inlineEditor){inlineEditor.redactorFacade.setCustomShowInsertLinkModal(function(){if(isImageEditingInProgress()){addLinkToImage(inlineEditor);}});inlineEditor.redactorFacade.setCustomInsertLinkAction(_imageEditing,function(linkValue,checked){var image=$(_imageEditing.getActiveImage());_imageEditing.stopEditingImage();linkImage(image,linkValue,checked);_imageEditing.addWrappers();});inlineEditor.redactorFacade.setCustomRemoveLinkFromImage(function(){if(isImageEditingInProgress()){removeLinkFromImage(inlineEditor);}});inlineEditor.redactorFacade.setCustomHtmlToggle(function(){if(_imageEditing){_imageEditing.executeAfterSaving(function(){showHideCodeEditor.call(inlineEditor);});}else{showHideCodeEditor.call(inlineEditor);}});_imageEditing.notifyRedactorReady();};initRedactorCallback=function(inlineEditor){var redactor=this;var toolbar;removeEditorMask.call(inlineEditor);inlineEditor.redactorFacade.setCustomToolbarEvent(redactor,function(event){customToolbarEventCallback(event,inlineEditor);});inlineEditor.redactorFacade.onOnKeyDownIE(function quitFullScreen(evt){if(evt.keyCode===ESC&&_inFullscren&&(!isImageEditingInProgress())){$('.re-fullscreen').trigger('click');}});redactor.code.startSync();inlineEditor.storedHtml=redactor.code.get();initImageEditing.call(inlineEditor);inlineEditor.destroyed=true;inlineEditor.isRedactorInit=false;inlineEditor.changes=false;if(_autoSave){initInterval.call(inlineEditor);}
inlineEditor.destroyed=false;if(inlineEditor.editUrl){toolbar=inlineEditor.redactorFacade.getToolbar(redactor);injectAdvancedButton.call(inlineEditor,toolbar);}};blurCallback=function(evt,inlineEditor){if(executingBlurCallback){return;}
if(inlineEditor.redactorFacade.isBlurCommingFromModal(evt)){return;}
executingBlurCallback=true;window.dnn.utils.PendingSavesManager.addPendingSave(inlineEditor.moduleId);if(inlineEditor.visual){unbindImageEditing.call(inlineEditor);if(_imageEditing){_history=_imageEditing.getHistory();_imageEditing.destroy(function nullifyImageAndSyncEditing(){executingBlurCallback=false;_imageEditing=null;});}else{initImageEditing.call(inlineEditor);if(_history){_imageEditing.setHistory(_history);_history=null;}}
inlineEditor.redactorFacade.toggle();}
inlineEditor.module.off('.imageEditing');destroyEditor.call(inlineEditor);};focusCallback=function(inlineEditor){_changeCallbackEnabled=true;setTimeout(function addWrappers(){if(_imageEditing){_imageEditing.addWrappers();}},0);};changeCallback=function(inlineEditor){if(!_changeCallbackEnabled){return;}
inlineEditor.changes=true;window.dnn.utils.PendingSavesManager.addPendingSave(inlineEditor.moduleId);if(_imageEditing){return;}
if(typeof inlineEditor.onChangeCallback==='function'){var currentHtml=inlineEditor.redactorFacade.get();if(!isTheSameHtmlContent.call(inlineEditor,currentHtml)){inlineEditor.onChangeCallback();}}};imageUploadCallback=function(e,image,json){var $element,$img,src;if(image&&image.filelink){$element=this.$element;$img=$element.find('img[src$="'+image.filelink+'"]');if($img.length>0){src=$img.attr('src');$img.on('load',function(){var offsetTop=$img.offset().top-$element.offset().top-$('#image-edit-bar').outerHeight(true);setTimeout(function(){$img.click();$element.scrollTop(offsetTop);},100);}).attr('src','').attr('src',src).css('max-width','100%');}}};areRedactorResourcesLoaded=function(){return _culture&&_resxRedactor&&Object.keys(_resxRedactor).length;};initRedactor=function initRedactorHandler(){if(!areRedactorResourcesLoaded()){setTimeout($.proxy(initRedactor,this),TIME_OUT_FOR_WAITING_RESOURCES);}else{initRedactorWithResourcesLoaded.call(this);};};initRedactorWithResourcesLoaded=function initRedactorWithResourcesLoadedHandler(){var self;if(window.dnn.HTMLPro.redactorActive){return;}
window.dnn.HTMLPro.redactorActive=true;this.isRedactorInit=true;self=this;self.visual=false;_inFullscren=false;var resxSettings={culture:_culture,resxRedactor:_resxRedactor};self.redactorFacade.setConfig(_redactorFacadeConfiguration,resxSettings);self.redactorFacade.initRedactor(_resxRedactor,function(){postInitRedactorCallback(self);},{allowedTags:['a','abbr','acronym','address','applet','area','article','aside','audio','b','base','basefont','bdi','bdo','big','blockquote','body','br','button','canvas','caption','center','cite','code','col','colgroup','datalist','dd','del','details','dfn','dialog','dir','div','dl','dt','em','embed','fieldset','figcaption','figure','font','footer','form','frame','frameset','h1','h2','h3','h4','h5','h6','head','header','hr','html','i','iframe','img','input','ins','kbd','keygen','label','legend','li','link','main','map','mark','menu','menuitem','meta','meter','nav','noframes','noscript','object','ol','optgroup','option','output','p','param','pre','progress','q','rp','rt','ruby','s','samp','script','section','select','small','source','span','strike','strong','style','sub','summary','sup','table','tbody','td','textarea','tfoot','th','thead','time','title','tr','track','tt','u','ul','var','video','wbr','inline'],deniedTags:[],buttons:['formatting','|','bold','italic','underline','|','orderedlist','unorderedlist','|','outdent','indent','|','|','link','file','|','html','|'],plugins:['dnnImageUpload','advancedmode'],imageTypes:['image/png','image/jpeg','image/gif','image/bmp'],removeEmpty:false,cleanSpaces:false,inlineTags:[],paragraphy:false,focus:true,shortcuts:true,convertDivs:false,imageResizable:false,imageLink:true,imagePosition:false,allowImageEditor:false,imageEditable:false,convertLinks:false,paragraphize:false,replaceDivs:false,observeImages:false,cleanFontTag:false,imageUpload:this.uploadUrl,imageGetJson:this.getImage,zIndexMax:1100,initCallback:function(){initRedactorCallback.call(this,self);},blurCallback:function(evt){blurCallback(evt,self);},focusCallback:function(){focusCallback(self);},changeCallback:function(){changeCallback(self);},imageUploadCallback:function(e,image,json){imageUploadCallback.call(this,e,image,json);},dropdownShowCallback:function dropDownShowCallbackHandler(args){if(args.key!=="formatting"){return;}
if(!_imageEditing){return;}
if(_imageEditing.isEditingInProcess()){_imageEditing.stopEditingImage();}
_imageEditing.removeWrappers();}});_moduleWithRedactor=self.module;if(typeof self.onEditorInitCallback==="function"){self.onEditorInitCallback.call(self);}};cleanHtml=function(html){return html.replace(/\>\s+/gm,'>').replace(/\s+\</gm,'<').replace(/ unselectable="on"/gm,'');};isTheSameHtmlContent=function(html){return cleanHtml(this.storedHtml)===cleanHtml(html);};saveEditor=function(successCallback,redactorWillBeDestroyed){var self=this,currentHtml,sf,savingLayer,progress,redactorBox;if(!self.autoSaveEnabled){return;}
if(self.destroyed){if(typeof successCallback==='function'){successCallback.call(this);}
return;}
self.changes=false;if(_imageEditing){_imageEditing.removeWrappers();}
var syncCallback=$.proxy(function(){currentHtml=self.redactorFacade.get();if(_imageEditing){_imageEditing.addWrappers();}
if(isTheSameHtmlContent.call(self,currentHtml)){if(typeof successCallback==='function'){successCallback.call(self);}
return;}
this.storedHtml=currentHtml;if(redactorWillBeDestroyed){savingLayer=$(_savingLayer);$('body').append(savingLayer);self.savingLayer=$('.dnnImageEditingSavingLayer');progress=savingLayer.find('.progressA');redactorBox=self.module.parent();savingLayer.css({width:redactorBox.css('width'),height:redactorBox.css('height')});savingLayer.offset(redactorBox.offset());progress.animate({width:'99%'},TIME_PROGRESS_BAR_SAVE_LAYER);}
sf=$.ServicesFramework(self.moduleId);$.ajax({type:'POST',url:self.saveUrl,beforeSend:sf.setModuleHeaders,data:{HtmlText:currentHtml},success:function(data){if(savingLayer){savingLayer.remove();savingLayer=null;}
if(typeof self.externalSaveSuccessCallback==="function"){self.externalSaveSuccessCallback(data);}
if(typeof successCallback==="function"){successCallback.call(self);}},error:function(xhr,status,error){var response,message;if(savingLayer){savingLayer.remove();}
response=$.parseJSON(xhr.responseText);message=response.ExceptionMessage||response.Message;$.dnnAlert({title:_resxInlineEditor.errorSavingText,text:message?message.replace(/^"(.+(?="$))"$/,'$1'):""});}});},this);self.redactorFacade.sync(syncCallback);};autosaveEditor=function(){if(this.changes===false||this.visual){return;}
if(isImageEditingInProgress()){return;}
saveEditor.call(this);};destroyEditor=function(finalCallback){var self,saveCallback,destroyCallback;if(this.destroyed){return;}
this.isRedactorInit=false;this.changes=false;endInterval.call(this);self=this;saveCallback=function(){if(_imageEditing){_imageEditing=null;}
$(window).off('keydown.dnnRedactorIE');_moduleWithRedactor=null;var destroyCallback=function(){self.destroyed=true;addEditorMask.call(self);if(typeof finalCallback==='function'){finalCallback.call(self);}
window.dnn.HTMLPro.redactorActive=false;window.dnn.utils.PendingSavesManager.completePendingSave(self.moduleId);executingBlurCallback=false;}
self.redactorFacade.sync(function syncCallBack(){changeCallback(self);self.redactorFacade.destroy(destroyCallback);_changeCallbackEnabled=false;});};destroyCallback=function destroyImageEditingCallback(){if(_autoSave){saveEditor.call(self,saveCallback,true);}else{saveCallback.call(self);}};if(_imageEditing){_imageEditing.destroy(destroyCallback);}else{destroyCallback.call(this,null,true);}};initImageEditing=function(){_imageEditing=new window.dnn.HTMLPro.ImageEditing(this.module,this.redactorFacade,this.siteRoot.replace('API/',''),this.sfImage,this.siteImageRoot+'/SaveImageStream',this.siteImageRoot+'/ProxyImage',_resxImageEditing);bindImageEditing.call(this);};bindImageEditing=function(){var self=this;this.module.on('hideToolbar.imageEditing',function enableAutosave(){self.redactorFacade.sync();initInterval.call(self);});this.module.on('showToolbar.imageEditing',function disableAutosave(){endInterval.call(self);});};unbindImageEditing=function(){this.module.off('.imageEditing');};injectAdvancedButton=function(redactorToolbar){var self,advancedButton;self=this;advancedButton=redactorToolbar.find('.re-advancedmode');advancedButton.on('click',function(evt){if(_inFullscren){$('.re-fullscreen').trigger('click');_beforeAdvancedWasInFullScreen=true;}else{_beforeAdvancedWasInFullScreen=false;}
evt.preventDefault();destroyEditor.call(self,advancedButtonSaveCallback);});};advancedButtonSaveCallback=function(){location.href=this.editUrl;setTimeout(function(){var $modal=$('#iPopUp');var $window=$(window);var newHeight=$window.height()-46;var newWidth=$window.width()-220;$modal.dialog({height:newHeight,width:newWidth});$modal.dialog({position:'center'});var loading=$modal.prev("div.dnnLoading");loading.css({width:$modal.width(),height:$modal.height()});},0);};localize=function(){if(!_resxInlineEditor||Object.keys(_resxInlineEditor).length===0){return;}
_savingLayer=_savingLayer.replace('{0}',_resxInlineEditor.savingChanges);};linkImage=function(image,url,openLinkInANewTab){var tag;if(!image||!url||typeof url!=='string'){return;}
tag='<a href="';if(url.search(/^https?:\/\//)!==0){url='http://'+url;}
tag+=url+'"';if(openLinkInANewTab){tag+=' target="_blank"';}
tag+='></a>';if(image.parent().is('a')){image.unwrap();}
image.wrap(tag);};unlinkImage=function unlinkImage(image){if(!image){return;}
if(image.parent().is('a')){image.unwrap();}};InlineEditing.setCulture=function setResx(culture){_culture=culture.replace('-','_');};InlineEditing.setResx=function setResx(resx){_resxInlineEditor=resx;localize();};InlineEditing.setRedactorResx=function setRedactorResx(resx,culture){_resxRedactor=resx;_culture=culture;};InlineEditing.setImageEditingResx=function setImageEditingResx(resx){_resxImageEditing=resx;window.dnn.HTMLPro.ImageEditing.localize(_resxImageEditing);};return InlineEditing;}());window.dnn.HTMLPro.InlineEditing=InlineEditingClass;}).call(this);