
﻿if(typeof dnn==="undefined"||dnn===null){dnn={};};﻿if(typeof dnn.ContentLayout==="undefined"||dnn.ContentLayout===null){dnn.ContentLayout={};};(function($){$.fn.dnnModuleLayout=function(dialog,options){if(!this.data("dnnModuleLayout")){this.data("dnnModuleLayout",new dnnModuleLayout(this,dialog,options));}
return this;};var dnnModuleLayout=function(container,moduleDialog,options){this.options=options;this.container=container;this.moduleDialog=moduleDialog;this.init();};dnnModuleLayout.prototype={constructor:dnnModuleLayout,init:function(){this.options=$.extend({},$.fn.dnnModuleLayout.defaultOptions,this.options);this._getService().request('GetContentLayoutTemplates','GET',{},$.proxy(this._getLayoutTemplates,this));},_getLayoutTemplates:function(data){var list=this.container.find('.dnnLayoutList .listContainer ul');for(var i in data){if(data.hasOwnProperty(i)){var dataItem=data[i];var item=$('<li class="">'+'<a href="#">'+'<img src="'+dataItem.icon+'" />'+'<span class="title">'+dataItem.name+'</span>'+'<span class="button"></span>'+'</a>'+'</li>');item.data('layout',dataItem);item.click($.proxy(this._itemClick,this));list.append(item);}}
this._initScrollView();},_itemClick:function(e){var dataItem=$(e.currentTarget).data('layout');var templateId=dataItem.id;this.moduleDialog.showProgressBar();this.moduleDialog.addModule(dnn.ContentLayout.desktopModuleId,function(tabModuleId){var serviceController=new dnn.dnnModuleService({service:'DnnCorp/ContentLayout',controller:'Service',async:false,moduleId:tabModuleId});var successCallback=function successCallbackHandler(data){$(document).trigger("changeOnPageContent");}
serviceController.request('UpdateLayoutFromTemplate','POST',{TemplateId:templateId},successCallback);},true);return false;},_initScrollView:function(){var WAIT_TIME_FOR_DOM_READY_IN_FIREFOX=200;setTimeout($.proxy(function(){var container=this.container.find(".dnnLayoutList .listContainer");if(container.data('jsp')){container.data('jsp').reinitialise();}else{container.jScrollPane();}},this),WAIT_TIME_FOR_DOM_READY_IN_FIREFOX);},_getService:function(){if(!this._serviceController){this._serviceController=new dnn.dnnModuleService({service:'DnnCorp/ContentLayout',controller:'Service'});}
return this._serviceController;}}
$.fn.dnnModuleLayout.defaultOptions={};var layoutInitialized=false;var generateLayout=function(title){return $('<div class="dnnDialogTitle">'+'<span class="dnnButton back"></span>'+'<span class="title">'+title+'</span>'+'</div>'+'<div class="dnnDialogBody dnnLayoutList">'+'<div class="listContainer"><ul></ul></div>'+'</div>');};var checkLayoutModuleVisible=function(){var moduleDialog=dnn.ContentEditorManager.getModuleDialog();var $dialogElement=moduleDialog.getElement();var moduleList=$dialogElement.find('.dnnModuleList ul');var parentPane=moduleDialog.getModuleManager().getPane().data('parentpane');var $layoutItem=moduleList.find('.dnnModuleItem[data-moduleid="'+dnn.ContentLayout.desktopModuleId+'"]');if(parentPane!=null){$layoutItem.hide();}else{$layoutItem.show();}}
var addModuleEventHandler=function(desktopModuleId,desktopModuleName){dnn.ContentLayout.desktopModuleId=desktopModuleId;dnn.ContentLayout.desktopModuleName=desktopModuleName;var moduleDialog=dnn.ContentEditorManager.getModuleDialog();var $dialogElement=moduleDialog.getElement();var moduleList=$dialogElement.find('.dnnModuleList ul');var $layoutItem=moduleList.find('.dnnModuleItem[data-moduleid="'+desktopModuleId+'"]');if($layoutItem.length){var pageLayout=generateLayout(desktopModuleName);moduleDialog.addPage('dnnLayout',pageLayout);pageLayout.find('.dnnButton.back').click(function(){moduleDialog.showPage(0);});$layoutItem.click(function(e){moduleDialog.showPage('dnnLayout');e.preventDefault();e.stopImmediatePropagation();});}
moduleDialog.getElement().on('dialogopen',function(e){checkLayoutModuleVisible();}).on('addmodulecomplete',function(e,newModule){dnn.ContentEditorManager.catchSortEvents(function(){newModule.trigger('editmodule');});}).on('pageChanged',function(e,page){if(!layoutInitialized&&page.hasClass('dnnLayout')){page.dnnModuleLayout(moduleDialog,{});layoutInitialized=true;}});checkLayoutModuleVisible();}
return{addModuleHandler:addModuleEventHandler};})(jQuery);