
﻿
window.dnn=dnn||{};window.dnn.personalizedTabs=dnn.personalizedTabs||{};window.dnn.personalizedTabs.rules=dnn.personalizedTabs.rules||{};(function IIFE(){var DeviceTypeRuleClass;DeviceTypeRuleClass=(function IIFE(){'use strict';var HTML_PATH="Assests/Html/Rules/DeviceTypeRuleTemplate.html";var _templateLoader,_resx;var getViewModel,remove;DeviceTypeRule.class='DeviceTypeRule';DeviceTypeRule.type='Class';DeviceTypeRule.template;DeviceTypeRule.allowMultipleInstances=false;function DeviceTypeRule(onDeleteRuleCallback,resx){_resx=resx;this._id="";this._viewModel={};this._ruleElement=null;this.onDeleteRuleCallback=onDeleteRuleCallback;_templateLoader=window.dnn.personalizedTabs.TemplateLoader;if(!DeviceTypeRule.template){_templateLoader.readHtmlTemplate(dnn.getVar('dnn_content_personalization_resourceroot')+HTML_PATH,function(template){DeviceTypeRule.template=template;});}}
getViewModel=function(self,data){self._viewModel={id:self._id,remove:remove,self:self,resx:_resx,mobileSelected:ko.observable(false),tabletSelected:ko.observable(false),pcSelected:ko.observable(false),anyDeviceTypeSelected:ko.observable(0).extend({validation:{validator:function(){if(self._viewModel.mobileSelected){return self._viewModel.mobileSelected()||self._viewModel.tabletSelected()||self._viewModel.pcSelected();}
return false;},message:_resx.RulesDeviceTypeValitationMessage}})};self._viewModel.mobileSelected.subscribe(function(){var oldValue=self._viewModel.anyDeviceTypeSelected();self._viewModel.anyDeviceTypeSelected(oldValue+1);});self._viewModel.tabletSelected.subscribe(function(){var oldValue=self._viewModel.anyDeviceTypeSelected();self._viewModel.anyDeviceTypeSelected(oldValue+1);});self._viewModel.pcSelected.subscribe(function(){var oldValue=self._viewModel.anyDeviceTypeSelected();self._viewModel.anyDeviceTypeSelected(oldValue+1);});if(data){self._viewModel.mobileSelected(data.Mobile);self._viewModel.tabletSelected(data.Tablet);self._viewModel.pcSelected(data.Pc);};self._viewModel.validationObservable=ko.validatedObservable({anyDeviceTypeSelected:self._viewModel.anyDeviceTypeSelected});};remove=function(){if(this.self.onDeleteRuleCallback&&typeof this.self.onDeleteRuleCallback==='function'){this.self.onDeleteRuleCallback(this.id);}};DeviceTypeRule.getId=function(){return"DeviceTypeRule";};DeviceTypeRule.getName=function(resx){return resx.RulesDeviceTypeName;};DeviceTypeRule.loadTemplate=function(callback){if(!DeviceTypeRule.template){_templateLoader.readHtmlTemplate(dnn.getVar('dnn_content_personalization_resourceroot')+HTML_PATH,function(template){DeviceTypeRule.template=template;callback();});}else{callback();}}
DeviceTypeRule.prototype.getId=function(){return this._id;};DeviceTypeRule.prototype.injectRule=function(parentElement,afterInjectCallback,data){var self=this;DeviceTypeRule.loadTemplate(function(){var dateNow=new Date().getTime();var html=DeviceTypeRule.template.replace(/\{0\}/g,dateNow);parentElement.append(html);self._id=dateNow;self._ruleElement=$("#{0}".replace(/\{0\}/g,self._id));getViewModel(self,data);ko.applyBindings(self._viewModel,self._ruleElement[0],{decorateElement:true,insertMessages:true,deep:true});afterInjectCallback(self,parentElement,self._viewModel.validationObservable);});}
DeviceTypeRule.prototype.getDataToBeSent=function(){if(!this._viewModel){return;}
return{type:"DeviceTypeRule",Mobile:this._viewModel.mobileSelected(),Tablet:this._viewModel.tabletSelected(),Pc:this._viewModel.pcSelected()};}
DeviceTypeRule.prototype.freeContext=function(){var element=$("#{0}".replace(/\{0\}/g,this._id));ko.cleanNode(element);}
DeviceTypeRule.prototype.doesRuleAllowMultipleInstances=function(){return DeviceTypeRule.allowMultipleInstances;};DeviceTypeRule.prototype.getRuleClass=function(){return DeviceTypeRule.class;};return DeviceTypeRule;})();window.dnn.personalizedTabs.rules.DeviceTypeRule=DeviceTypeRuleClass;}).call(this);