
﻿
window.dnn=dnn||{};window.dnn.personalizedTabs=dnn.personalizedTabs||{};window.dnn.personalizedTabs.rules=dnn.personalizedTabs.rules||{};(function IIFE(){var LastActivityDateRuleClass;LastActivityDateRuleClass=(function IIFE(){'use strict';var HTML_PATH="Assests/Html/Rules/LastActivityDateRuleTemplate.html";var _templateLoader,_service,_resx;var getService,getServiceUrl,onBeforeSend,makeRequest,getViewModel,remove;LastActivityDateRule.class='LastActivityDateRule';LastActivityDateRule.type='Class';LastActivityDateRule.template;LastActivityDateRule.allowMultipleInstances=false;function LastActivityDateRule(onDeleteRuleCallback,resx){_resx=resx;this._id="";this._viewModel={};this._ruleElement=null;this.onDeleteRuleCallback=onDeleteRuleCallback;_templateLoader=window.dnn.personalizedTabs.TemplateLoader;if(!LastActivityDateRule.template){_templateLoader.readHtmlTemplate(dnn.getVar('dnn_content_personalization_resourceroot')+HTML_PATH,function(template){LastActivityDateRule.template=template;});}}
getService=function(){if(!_service){_service=$.dnnSF();}
return _service;};getServiceUrl=function(service,controller){return getService().getServiceRoot(service)+controller+'/';};onBeforeSend=function(xhr){getService().setModuleHeaders(xhr);};makeRequest=function(service,controller,method,type,params,data,callback,errorCallBack,sync){var d=data;if(params&&params.dataType==='json'){d=JSON.stringify(data);}
var request={url:getServiceUrl(service,controller)+method,type:type,data:d,async:!sync,beforeSend:$.proxy(onBeforeSend,this),success:function(data){if(typeof callback=="function"){callback(data);}},error:function(xhr){if(typeof errorCallBack=="function"){errorCallBack(xhr);}}}
$.extend(request,params);$.ajax(request);};getViewModel=function(self,data){self._viewModel={id:self._id,remove:remove,self:self,resx:_resx,availablePeriods:ko.observableArray(LastActivityDateRule.availablePeriods),selectedPeriod:ko.observable().extend({required:true,})};if(data){LastActivityDateRule.availablePeriods.forEach(function(period,idx){if(data.Period==period.Period){self._viewModel.selectedPeriod(period);}});};self._viewModel.validationObservable=ko.validatedObservable({selectedPeriod:self._viewModel.selectedPeriod});};remove=function(){if(this.self.onDeleteRuleCallback&&typeof this.self.onDeleteRuleCallback==='function'){this.self.onDeleteRuleCallback(this.id);}};LastActivityDateRule.getId=function(){return"LastActivityDateRule";};LastActivityDateRule.getName=function(resx){return resx.RulesLastActivityDateName;};LastActivityDateRule.loadTemplate=function(callback){if(!LastActivityDateRule.template){_templateLoader.readHtmlTemplate(dnn.getVar('dnn_content_personalization_resourceroot')+HTML_PATH,function(template){LastActivityDateRule.template=template;callback();});}else{callback();}}
LastActivityDateRule.initStaticElements=function(){LastActivityDateRule.availablePeriods=[];makeRequest('ContentPersonalization','LastActivityDate','GetPeriods','get',null,null,function(data){data.forEach(function(period,idx){LastActivityDateRule.availablePeriods.push(period);});});}
LastActivityDateRule.prototype.getId=function(){return this._id;};LastActivityDateRule.prototype.injectRule=function(parentElement,afterInjectCallback,data){var self=this;LastActivityDateRule.loadTemplate(function(){var dateNow=new Date().getTime();var html=LastActivityDateRule.template.replace(/\{0\}/g,dateNow);parentElement.append(html);self._id=dateNow;self._ruleElement=$("#{0}".replace(/\{0\}/g,self._id));getViewModel(self,data);ko.applyBindings(self._viewModel,self._ruleElement[0],{decorateElement:true,insertMessages:true,deep:true});afterInjectCallback(self,parentElement,self._viewModel.validationObservable);});}
LastActivityDateRule.prototype.getDataToBeSent=function(){if(!this._viewModel){return;}
return{type:"LastActivityDateRule",Period:this._viewModel.selectedPeriod().Period};}
LastActivityDateRule.prototype.freeContext=function(){var element=$("#{0}".replace(/\{0\}/g,this._id));ko.cleanNode(element);}
LastActivityDateRule.prototype.doesRuleAllowMultipleInstances=function(){return LastActivityDateRule.allowMultipleInstances;};LastActivityDateRule.prototype.getRuleClass=function(){return LastActivityDateRule.class;};return LastActivityDateRule;})();window.dnn.personalizedTabs.rules.LastActivityDateRule=LastActivityDateRuleClass;}).call(this);