
﻿
window.dnn=dnn||{};window.dnn.personalizedTabs=dnn.personalizedTabs||{};window.dnn.personalizedTabs.rules=dnn.personalizedTabs.rules||{};(function IIFE(){var PageVisitedRuleClass;PageVisitedRuleClass=(function IIFE(){'use strict';var HTML_PATH="Assests/Html/Rules/PageVisitedRuleTemplate.html";var FIRST_ITEM={key:"",value:""};var _templateLoader,_service,_resx;var getService,getServiceUrl,getViewModel,remove,selectPage,documentClickHandler,hidePagePicker,getPagePickerOffset;PageVisitedRule.class='PageVisitedRule';PageVisitedRule.type='Class';PageVisitedRule.template;PageVisitedRule.allowMultipleInstances=true;function PageVisitedRule(onDeleteRuleCallback,resx){_resx=resx;FIRST_ITEM.value=_resx.RulesPageVisitedFirstElementText;this._id="";this._viewModel={};this._ruleElement=null;this.onDeleteRuleCallback=onDeleteRuleCallback;this.selectedNode=null;_templateLoader=window.dnn.personalizedTabs.TemplateLoader;if(!PageVisitedRule.template){_templateLoader.readHtmlTemplate(dnn.getVar('dnn_content_personalization_resourceroot')+HTML_PATH,function(template){PageVisitedRule.template=template;});}}
getService=function(){if(!_service){_service=$.dnnSF();}
return _service;};getServiceUrl=function(service,controller){return getService().getServiceRoot(service)+controller+'/';};getViewModel=function(self,data){self._viewModel={id:self._id,remove:remove,self:self,resx:_resx,selectPage:selectPage,selectedPage:null,firstItem:FIRST_ITEM,pageListId:self._id+"_PageList",pageListPlaceHolderId:self._id+"_PageListPlaceHolder"};self._viewModel.pagePickerVisible=ko.observable(false);self._viewModel.showPagePicker=function(){self._viewModel.pagePickerVisible(true);$("#"+self._viewModel.pageListId).position({my:"left top",at:"left top",of:"#"+self._viewModel.pageListPlaceHolderId});$("#"+self._viewModel.pageListId+" .selected-value").trigger("click");var eventArgs={};eventArgs.viewModel=self._viewModel;$(document).off("click."+self._viewModel.id);$(document).on("click."+self._viewModel.id,eventArgs,documentClickHandler);};if(data){self._viewModel.selectedPage={key:data.Tab.TabId,value:data.Tab.Name};};self._viewModel.internalSelectedPage=ko.observable(self._viewModel.selectedPage?self._viewModel.selectedPage.value:self._viewModel.firstItem.value);self._viewModel.anyPageSelected=ko.observable(1).extend({validation:{validator:function(){return(self._viewModel.selectedPage&&self._viewModel.selectedPage.key!="");},message:_resx.RulesPageVisitedValidationMessage}});self._viewModel.validationObservable=ko.validatedObservable({anyPageSelected:self._viewModel.anyPageSelected});};documentClickHandler=function(eventObject){var $pageList=$("#"+eventObject.data.viewModel.pageListId);var $listPlaceHolder=$("#"+eventObject.data.viewModel.pageListPlaceHolderId);var clickedElement=eventObject.target;if(!$.inContainer($pageList,clickedElement)&&!$.inContainer($listPlaceHolder,clickedElement)){$("#"+eventObject.data.viewModel.pageListId+" .selected-value").trigger("click");hidePagePicker($pageList,eventObject.data.viewModel,0);}
if($.inContainer($pageList,clickedElement)){hidePagePicker($pageList,eventObject.data.viewModel,0);}};hidePagePicker=function($pageList,viewModel,count){if($(".selected-value",$pageList).hasClass("opened")){if(count<5){setTimeout(function launchHidePagePicker(){hidePagePicker($pageList,viewModel,count+1);},200);}}else{viewModel.pagePickerVisible(false);$(document).off("click."+viewModel.id,documentClickHandler);}}
selectPage=function(selectedPage){this.self._viewModel.selectedPage=selectedPage;this.self._viewModel.anyPageSelected(-1*this.self._viewModel.anyPageSelected());this.self._viewModel.internalSelectedPage(selectedPage.value);$("#"+this.self._viewModel.pageListId+" .selected-value").trigger("click");hidePagePicker($("#"+this.self._viewModel.pageListId),this.self._viewModel,0);};remove=function(){$("#"+this.self._viewModel.pageListId).remove();if(this.self.onDeleteRuleCallback&&typeof this.self.onDeleteRuleCallback==='function'){this.self.onDeleteRuleCallback(this.id);}};PageVisitedRule.getId=function(){return"PageVisitedRule";};PageVisitedRule.getName=function(resx){return resx.RulesPageVisitedName;};PageVisitedRule.loadTemplate=function(callback){if(!PageVisitedRule.template){_templateLoader.readHtmlTemplate(dnn.getVar('dnn_content_personalization_resourceroot')+HTML_PATH,function(template){PageVisitedRule.template=template;callback();});}else{callback();}}
PageVisitedRule.prototype.getId=function(){return this._id;};PageVisitedRule.prototype.injectRule=function(parentElement,afterInjectCallback,data){var self=this;PageVisitedRule.loadTemplate(function(){var dateNow=new Date().getTime();var html=PageVisitedRule.template.replace(/\{0\}/g,dateNow);parentElement.append(html);self._id=dateNow;self._ruleElement=$("#{0}".replace(/\{0\}/g,self._id));getViewModel(self,data);ko.applyBindings(self._viewModel,self._ruleElement[0],{decorateElement:true,insertMessages:true,deep:true});afterInjectCallback(self,parentElement,self._viewModel.validationObservable);});}
PageVisitedRule.prototype.getDataToBeSent=function(){if(!this._viewModel){return;}
return{type:"PageVisitedRule",Tab:{TabId:this._viewModel.selectedPage.key,Name:this._viewModel.selectedPage.value}};}
PageVisitedRule.prototype.freeContext=function(){var element=$("#{0}".replace(/\{0\}/g,this._id));ko.cleanNode(element);}
PageVisitedRule.prototype.doesRuleAllowMultipleInstances=function(){return PageVisitedRule.allowMultipleInstances;};PageVisitedRule.prototype.getRuleClass=function(){return PageVisitedRule.class;};return PageVisitedRule;})();window.dnn.personalizedTabs.rules.PageVisitedRule=PageVisitedRuleClass;}).call(this);