
﻿"use strict";define(['jquery','knockout','templatePath/scripts/config','templatePath/scripts/PersonaBarDialog'],function($,ko,cf,PersonaBarDialog){var helper,bindViewModel,rootFolder,utility,appId,appSecret,authPage,parentFolder,parentFolderId;var siteConfig=cf.init();var init=function(koObject,connectionHelper,pluginFolder,util){helper=connectionHelper;bindViewModel=koObject;rootFolder=pluginFolder;utility=util;window.testModel=bindViewModel;bindViewModel.parentFolder=ko.observable('');bindViewModel.parentFolderId=ko.observable('');bindViewModel.parentFolderId.subscribe(onParentFolderIdChanged);bindViewModel.foldersData=ko.observableArray([]);if(typeof dnn==='undefined'){window.Sys=!window.Sys?window.top.Sys:window.Sys;window.dnn=!window.dnn?window.top.dnn:window.dnn;}
processData();setTimeout(function(){$('#connector-Box input.senseField').blur(onFieldBlur);},0);};var onSave=function(koObject){if(typeof bindViewModel.parentFolder!=="undefined"){bindViewModel.configurations.push({name:'ParentFolder',value:ko.protectedObservable(bindViewModel.parentFolder())});}
if(typeof bindViewModel.parentFolderId!=="undefined"){bindViewModel.configurations.push({name:'ParentFolderId',value:ko.protectedObservable(bindViewModel.parentFolderId())});}}
var onFieldBlur=function(){var $this=$(this);var changed=($this.hasClass('appId')&&$this.val()!=appId)||($this.hasClass('appSecret')&&$this.val()!=appSecret);if(changed){bindViewModel.connected(false);}}
var onParentFolderIdChanged=function(){var selectedId=bindViewModel.parentFolderId();var options=document.getElementById('BoxFoldersDropDown').options;for(var i=0;i<options.length;i++){var option=options[i];if(option.value==selectedId){bindViewModel.parentFolder(option.text);break;}}}
var processData=function(){for(var i=bindViewModel.configurations.length-1;i>=0;i--){var config=bindViewModel.configurations[i];if(config.name!='AppId'&&config.name!='AppSecret'){switch(config.name.toLowerCase()){case'connected':bindViewModel.connected(config.value()=='true');bindViewModel.configurations.splice(i,1);break;case'authpage':authPage=config.value();break;case"parentfolder":parentFolder=config.value();bindViewModel.configurations.splice(i,1);break;case"parentfolderid":parentFolderId=config.value();bindViewModel.configurations.splice(i,1);break;}}else if(config.name=='AppId'){appId=config.value();}else if(config.name=='AppSecret'){appSecret=config.value();}}
if(bindViewModel.connected()&&bindViewModel.foldersData().length==0){setTimeout(loadFoldersData,0);}}
var loadingFolders=false;var loadFoldersData=function(){if(loadingFolders){return;}
var foldersDropDown=$('#BoxFoldersDropDown');showLoading(foldersDropDown);utility.sf.moduleRoot='dnncorp/BoxConnector';utility.sf.controller='Services';utility.sf.get('GetAllFolders',{},function(data){bindViewModel.foldersData.removeAll();for(var i=0;i<data.length;i++){bindViewModel.foldersData.push({id:data[i].Id,path:data[i].Path});}
setTimeout(function(){if(typeof parentFolderId=="undefined"||parentFolderId==''){parentFolder='0';}
bindViewModel.parentFolderId(parentFolderId);hideLoading();},0);},function(xhr){var message=xhr.responseJSON.Message;if(message.indexOf('{')==0){message=JSON.parse(message)['error'];}
utility.notifyError(message);});}
var showLoading=function(element){var $loading=$('<div class="loading"></div>').html(bindViewModel.resx.Loading);element.after($loading);loadingFolders=true;}
var hideLoading=function(){$('#connector-Box .loading').remove();loadingFolders=false;}
var getCookie=function(name,success,fail){utility.sf.moduleRoot='dnncorp/BoxConnector';utility.sf.controller='Services';utility.sf.call('GET','GetAuthCookie',{},function(data){if(data.value){success(data.value);}else{fail();}},function(xhr){},null,null,false,true);}
var removeCookie=function(name){utility.sf.moduleRoot='dnncorp/BoxConnector';utility.sf.controller='Services';utility.sf.call('GET','RemoveAuthCookie',{},function(data){},function(xhr){},null,null,true,true);}
var onSaveComplete=function(){processData();if(!bindViewModel.connected()&&appId!=''&&appSecret!=''){showAuthWindow();}else{bindViewModel.inEdit(false);$('#connector-Box').slideUp(200,'linear');utility.notify(utility.resx.PersonaBar.txt_Saved,true);}}
var checkCookieTimer;var boxAuthCookieName='BoxAuthCookie';var cookieTimeout=500;var showAuthWindow=function(){utility.sf.moduleRoot='dnncorp/BoxConnector';utility.sf.controller='Services';utility.sf.call('GET','GetFolderMappingId',{},function(data){var url=authPage.replace('{0}',data);popupwindow(url,'BoxAuth',770,600);if(checkCookieTimer){clearTimeout(checkCookieTimer);}
checkCookieTimer=setTimeout(checkCookieForAuth,cookieTimeout);},function(xhr){utility.notifyError('Failed...');},null,null,true,false);}
var checkCookieForAuth=function(){getCookie(boxAuthCookieName,function(authCookie){removeCookie(boxAuthCookieName);eval(authCookie);},function(){checkCookieTimer=setTimeout(checkCookieForAuth,cookieTimeout);});}
var popupwindow=function(url,title,width,height){var winLeft=window.screenLeft?window.screenLeft:window.screenX;var winTop=window.screenTop?window.screenTop:window.screenY;var left=winLeft+(window.innerWidth-width)/2;var top=winTop+(window.innerHeight-height)/2;var params='toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no,'+'width='+width+', height='+height+', top='+top+', left='+left;return window.open(url,title,params);}
var authCallback=window["BoxAuthCallback"]=function(success,message){if(message.indexOf('{')==0){message=JSON.parse(message)['error'];}
$('.personaBarDialog .actions .btn-cancel').click();if(!success){utility.notifyError(message);}else{utility.notify(bindViewModel.resx.AuthenticationSuccess,true);bindViewModel.connected(true);var c={name:'connected',value:ko.protectedObservable('true')};bindViewModel.configurations.push(c);loadFoldersData();processData();}}
var authenticate=function(conn,e){e.preventDefault();$.each(conn.configurations,function(i,v){v.value.commit();});saveConnection(conn,onSaveComplete);}
var onSaveConnection=false;var saveConnection=function(conn,success){if(onSaveConnection)return;onSaveConnection=true;if(conn.connector){conn.connector.onSave(conn);}
utility.sf.moduleRoot='dnncorp/personaBar';utility.sf.controller='connections';var postData={name:conn.name,configurations:[]};var allEmpty=true;var allFilled=true;for(var i=0;i<conn.configurations.length;i++){var c=conn.configurations[i];var value=c.value();postData.configurations.push({name:c.name,value:c.value()});if(c.name=='AppId'||c.name=='AppSecret'){if(value!=''){allEmpty=false;}else{allFilled=false;}}}
var primaryButtons=$('#connector-'+conn.name).find('a.primarybtn');if(!allEmpty&&!allFilled){primaryButtons.addClass('disabledbtn');onSaveConnection=false;return;}else{primaryButtons.removeClass('disabledbtn');}
utility.sf.call('POST','SaveConnection',postData,function(d){if(d&&d.Success){success();}else{utility.notifyError('Failed...');}
onSaveConnection=false;},function(){utility.notifyError('Failed...');onSaveConnection=false;},null,null,true,false);};var getActionButtons=function(){return[{className:'primarybtn',text:bindViewModel.resx.Save,action:function(conn,e){if(!bindViewModel.connected()){authenticate(conn,e);}else{conn.save(conn,e,function(success){onSaveComplete();});}}}];}
return{init:init,onSave:onSave,getActionButtons:getActionButtons}});